services:
  api: 
    build: .
    # container_name: --> 컨테이너 이름은 사람이 알아보기 쉬운 고정이름을 붙인다
    container_name: booklib-api
    ports:
      - "8000:8000"  # "호스트포트:컨테이너포트"
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads   # 내 컴퓨터 경로:컨테이너 경로
    depends_on:
      db:
        # db 컨테이너가 단순히 실행만 된 상태가 아니라 헬스체크(상태체크)를 통과해 정상적으로 접속 가능
        # 해진 뒤에 api를 실행한다. 
        # 생성 순서만 맞추는 것이 아니라 준비 완료까지 기다린다!
        condition: service_healthy

  web:
    build: .
    container_name: booklib-web
    ports:
      - "8501:8501"
    environment:
      # 컨테이너 안에서 api컨테이너에 접속할 때는 localhost가 아니라 docker-compose.yml에 적은
      # 주소로 사용해야 한다.
      API_URL: http://api:8000
    depends_on:
      # api컨테이너가 먼저 뜬 뒤 web을 실행 (순서만 보장)
      - api
    command: >
      streamlit run streamlit_app.py
      --server.address=0.0.0.0
      --server.port=8501

  db:
    image: postgres:17
    container_name: booklib-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - booklib_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  booklib_pgdata: